{% set name = "coreforecast" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coreforecast-{{ version }}.tar.gz
  sha256: 1f8a4afac9c04fd2d00995271dcb54c1a9353a6de6e89fc83cf26ff75a32a2ae

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - scikit-build-core
    - pip
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - importlib_resources  # [py<310]
    - numpy >=1.20.0

test:
  requires:
    - pytest
  files:
    - test_scalers.py
  commands:
    - pytest test_scalers.py

about:
  home: https://nixtla.github.io/coreforecast
  summary: Fast implementations of common forecasting routines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmoralez
